<?php
    $lang['number']   = 'Referência';
    $lang['date']     = 'Data da fatura';
    $lang['time']     = 'Hora da fatura';
    $lang['due']      = 'Código do Cliente';
    $lang['to']       = 'Cliente';
    $lang['from']     = 'Emissor';
    $lang['product']  = 'Designação';
    $lang['qty']      = 'Qnt';
    $lang['price']    = 'Preço';
    $lang['discount'] = 'Desco(%)';
    $lang['vat']      = 'IVA';
    $lang['total']    = 'Total';
    $lang['page']     = 'Pág.';
    $lang['page_of']  = 'of';
